// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://utafodjnqfkpfllftkqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0YWZvZGpucWZrcGZsbGZ0a3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkwMzczNzIsImV4cCI6MjA5NDYxMzM3Mn0.Bnw3KpCTQJgIfFqTZwkSq26e9ymdtR0TDr-MlIVX_lw";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);